Linear types (#222)
* typeModifier added to AST

* should be done; but error: i dont know what typeItemParser is expecting

* Parsing & AST done; did not pass test

* AST and Parser fully functioning

* unique test case added

* added typeModifiers to moduleInterface

* small fixes in AST

* finalising with docs added

* rm master's Parser, renamed old 'NewParser' to 'Parser'

* tried my best to merge; advises in convos are taken

* added type modifiers to updated Parser

* fix compilation errors in handling of unique type declarations

* Update foldStmts to pass source position as well as statements/expressions to folding functions.  Report source positions for uniqueness errors.

* Move uniqueness checking to after resource expansion, so it works for resources, too.

* Fix foldStmt and friends to also take a source position.  Fix uniqueness checking to include a source position in error reports.  Fix uniqueness checking to also report a uniqueness error when a unique output parameter/resource is used.  Change depiction of proc name for top-level module code to be more readable.

* add passing test case for unique io resource; remove failing case with unique structure.

* Minor update for changed show of top-level code proc.

* Document uniqueness; add Terry to list of contributors.

Co-authored-by: Sushi6006 <lin.terry.x2@gmail.com>